import { Check, Circle, LockKeyhole, PlaneTakeoff, Settings2, UsersRound } from "lucide-react";
import Link from "next/link";
import { getProfile, listPolicies, listTrips } from "@/application/dal/customer-data";
import { StarterPolicyImporter } from "@/features/policy/starter-policy-importer";

export const metadata = { title: "Set up SafarSet" };

export default async function OnboardingPage() {
  const [profile, policies, trips] = await Promise.all([getProfile(), listPolicies(), listTrips()]);
  const steps = [
    { complete: true, icon: LockKeyhole, title: "Account secured", body: "Your private SafarSet workspace is ready.", href: "/account", action: "Review account" },
    { complete: Boolean(profile.fullName && profile.homeAirport), icon: UsersRound, title: "Family defaults", body: "Name, home airport, and usual travel group.", href: "/settings", action: "Set family defaults" },
    { complete: policies.length > 0, icon: Settings2, title: "Travel rules", body: "Family, route, cabin, timing, and spend boundaries.", href: "/settings", action: "Set travel rules" },
    { complete: trips.length > 0, icon: PlaneTakeoff, title: "First real trip", body: "Import an issued itinerary or add it manually.", href: "/trips/new", action: "Add first trip" },
  ];
  const complete = steps.every((step) => step.complete);
  const completedCount = steps.filter((step) => step.complete).length;
  const progress = Math.round((completedCount / steps.length) * 100);
  return <div className="mx-auto max-w-4xl px-5 py-12 sm:px-8 lg:py-16"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-xs uppercase tracking-[.18em] text-[#147D92]">Four-step setup</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.05em]">Make SafarSet yours.</h1><p className="mt-3 max-w-2xl text-[#627D98]">Do this once. The agent then reuses your family and travel rules instead of asking the same questions.</p></div><div className="min-w-44"><div className="flex items-center justify-between text-xs"><span className="font-medium text-[#334E68]">{completedCount} of {steps.length} ready</span><span className="font-mono text-[#147D92]">{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#D9E2EC]" role="progressbar" aria-label="Setup progress" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100}><div className="h-full rounded-full bg-[#2CB1BC] transition-[width]" style={{ width: `${progress}%` }} /></div></div></div><p className="mt-5 rounded-xl bg-[#F0F4F8] px-4 py-3 text-sm text-[#52606D]"><strong className="text-[#102A43]">You are not starting at zero.</strong> Your private account is already complete, so setup begins at 25%.</p><div className="mt-8"><StarterPolicyImporter /></div><div className="space-y-3">{steps.map(({ complete: done, icon: Icon, title, body, href, action }, index) => <article className="flex flex-col gap-4 rounded-2xl border border-[#D9E2EC] bg-white p-5 sm:flex-row sm:items-center" key={title}><span className={`grid size-11 shrink-0 place-items-center rounded-xl ${done ? "bg-[#E3F8F8] text-[#147D92]" : "bg-[#F0F4F8] text-[#627D98]"}`}>{done ? <Check className="size-5" /> : <Icon className="size-5" />}</span><div className="flex-1"><p className="font-mono text-[10px] text-[#9FB3C8]">STEP {index + 1}</p><h2 className="mt-1 font-semibold">{title}</h2><p className="mt-1 text-sm text-[#627D98]">{body}</p></div><Link className="inline-flex justify-center rounded-lg border border-[#BCCCDC] px-4 py-2.5 text-sm font-medium text-[#334E68] hover:border-[#2CB1BC]" href={href}>{done ? "Review" : action}</Link></article>)}</div><div className="mt-8 flex items-center justify-between rounded-2xl bg-[#102A43] p-5 text-white"><div className="flex items-center gap-3">{complete ? <Check className="size-5 text-[#67E8E8]" /> : <Circle className="size-5 text-[#829AB1]" />}<p className="text-sm">{complete ? "Setup complete. The agent has enough context to help." : "You can leave and return. Progress is saved."}</p></div><Link className="text-sm font-medium text-[#67E8E8]" href={complete ? "/agent" : "/dashboard"}>{complete ? "Open agent →" : "Skip for now"}</Link></div></div>;
}
