"use client";

import { useActionState, useState } from "react";

import { AirportCombobox } from "@/components/airport-combobox";
import { saveAccountAction } from "./actions";

export function AccountForm({ profile }: Readonly<{ profile: { fullName: string; email: string; homeAirport: string; timezone: string; defaultAdults: number; defaultChildren: number } }>) {
  const [state, action, pending] = useActionState(saveAccountAction, null);
  const [homeAirport, setHomeAirport] = useState(profile.homeAirport);
  return <form action={action} className="space-y-6"><section className="rounded-2xl border border-[#D9E2EC] bg-white p-5 sm:p-7"><div><h2 className="text-lg font-semibold">You</h2><p className="mt-1 text-sm text-[#627D98]">Used for trip defaults and notifications.</p></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="block text-sm font-medium text-[#334E68]">Full name<input className="field" defaultValue={profile.fullName} name="fullName" required /></label><label className="block text-sm font-medium text-[#334E68]">Email<input className="field bg-[#F0F4F8]" value={profile.email} readOnly /></label><AirportCombobox label="Home airport" name="homeAirport" onChange={(airport) => setHomeAirport(airport.code)} value={homeAirport} /><label className="block text-sm font-medium text-[#334E68]">Timezone<select className="field" defaultValue={profile.timezone} name="timezone"><option value="Asia/Kolkata">India</option><option value="Europe/London">London</option><option value="Europe/Paris">Paris</option><option value="Asia/Dubai">Dubai</option><option value="Asia/Singapore">Singapore</option><option value="America/New_York">New York</option></select></label></div></section><section className="rounded-2xl border border-[#D9E2EC] bg-white p-5 sm:p-7"><h2 className="text-lg font-semibold">Usual travel group</h2><p className="mt-1 text-sm text-[#627D98]">SafarSet applies this household to new trips. You can change it later.</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="block text-sm font-medium text-[#334E68]">Adults<input className="field" defaultValue={profile.defaultAdults} max={12} min={1} name="defaultAdults" required type="number" /></label><label className="block text-sm font-medium text-[#334E68]">Children<input className="field" defaultValue={profile.defaultChildren} max={12} min={0} name="defaultChildren" required type="number" /></label></div></section>{state?.error && <p className="rounded-lg bg-[#FFF5F5] px-4 py-3 text-sm text-[#9B2C2C]">{state.error}</p>}{state?.success && <p className="rounded-lg bg-[#E3F8F8] px-4 py-3 text-sm text-[#147D92]">{state.success}</p>}<div className="flex justify-end"><button className="button-primary" disabled={pending} type="submit">{pending ? "Saving…" : "Save settings"}</button></div></form>;
}
